📈 add hotjar to site
ImpulsoGov/ImpulsoPrevine pull request #152
Opened 2023-11-22 19:24 UTC by LeviMacario

Temos uma necessidade importante em ter mais ferramentas de Análises para produto. 
Adicionei o hotjar ao ImpulsoPrevine visão capturar todas as sessões da área aberta e área logada.

2023-11-22 19:41 UTC, dlopes14 commented
@LeviMacario pode verificar a origem desses erros ? 
<img width="674" alt="image" src="https://github.com/ImpulsoGov/ImpulsoPrevine/assets/60981654/44887db6-629c-4de3-b402-326c240ab68f">
OBS : Eles já apareciam antes das alterações desse PR

2023-11-22 19:41 UTC, dlopes14 requested changes
@LeviMacario pode verificar a origem desses erros ? 
<img width="674" alt="image" src="https://github.com/ImpulsoGov/ImpulsoPrevine/assets/60981654/44887db6-629c-4de3-b402-326c240ab68f">
OBS : Eles já apareciam antes das alterações desse PR

2023-11-24 12:38 UTC, LeviMacario commented
Corrigido @dlopes14 . ✅

2023-11-24 13:11 UTC, dlopes14 approved these changes

2023-11-24 13:12 UTC, merged