Ajustes gestao individual usuarios
ImpulsoGov/ImpulsoPrevine pull request #175
Opened 2024-01-20 04:43 UTC by tainnaps

2024-01-23 20:40 UTC, LeviMacario requested changes

2024-01-23 20:40 UTC, LeviMacario commented on componentes/ModalCadastroUsuario/ModalCadastroUsuario.jsx
> +  const limparInputs = useCallback(() => {
Qual a necessidade de zerar antes todos os inputs?

2024-01-23 20:40 UTC, LeviMacario commented on componentes/TabelaGestaoUsuarios/TabelaGestaoUsuarios.jsx
> +    if (newValue !== null) {
Esse condicional dessa forma me aparenta um pouco redundante. basicamente o que muda de um caso para o outro é o que será inserido em "value:".

O que acha de experimentar algo assim?

```
const value = newValue !== null ? `${newValue.nome} - ${newValue.uf}` : newValue;
apiRef.current.setEditCellValue({ id, field, value });
```

2024-01-23 20:40 UTC, LeviMacario commented on services/gestaoUsuarios.js
>      requestData.append('nome_usuario', dados.nome);
Aqui nessas várias linhas com .append vale uma forma mais elegante de escrever. Pode ser uma desestruturação de objeto ou até mesmo um loop para preencher o requestData com o que vem em dados.
Tem algum campo de dados que não deve ser inserido em requestData? Caso não, algo assim pode fazer sentido:

```
const requestData = new FormData();

for (const [chave, valor] of Object.entries(dados)) {
      requestData.append(chave, valor);
}
```

O que acha?

2024-01-23 22:45 UTC, tainnaps commented on componentes/ModalCadastroUsuario/ModalCadastroUsuario.jsx
> +  const limparInputs = useCallback(() => {
@LeviMacario, olá!
A função `limparInputs` não é executada quando o componente é renderizado, apenas está sendo definida nessa linha. O hook `useCallback` está fazendo um cache da definição dessa função para que ela não seja redefinida a cada re-render do componente. Esse hook costuma ser útil quando uma função depende de algum estado ou prop por exemplo, o que não é o caso aqui. Acho que vale a pena remover o `useCallback` nessa situação.
A função `limparInputs` foi definida para ser executada apenas quando o cadastro de um novo usuário é feito com sucesso, resetando os dados exibidos nas inputs do formulário e deixando-o pronto pra receber novos dados de cadastro. Por isso ela é passada como callback para a função que é executada após submissão do formulário, na linha 177 desse arquivo. Executar essa função após o cadastro previne que a gestora de usuários cadastre o próximo usuário com algum dado errado, sem querer, caso esqueça de alterar o valor de alguma input no próximo cadastro.

2024-01-23 22:57 UTC, tainnaps commented on componentes/TabelaGestaoUsuarios/TabelaGestaoUsuarios.jsx
> +    if (newValue !== null) {
Obrigada pela sugestão! Implementado ✅

2024-01-24 13:05 UTC, LeviMacario commented on componentes/ModalCadastroUsuario/ModalCadastroUsuario.jsx
> +  const limparInputs = useCallback(() => {
Excelente @tainnaps , ficou super claro sim tua explicação e faz sentido manter assim.

2024-01-24 13:07 UTC, LeviMacario commented on componentes/TabelaGestaoUsuarios/TabelaGestaoUsuarios.jsx
> +    if (newValue !== null) {
Shooow!

2024-01-24 19:08 UTC, tainnaps commented on services/gestaoUsuarios.js
>      requestData.append('nome_usuario', dados.nome);
@LeviMacario tem sim alguns campos de `dados` que não devem ser passados na requisição. Eu posso fazer a desestruturação, já no parâmetro da função, apenas dos campos que vou usar na requisição, acha que faria mais sentido?

2024-01-31 13:29 UTC, LeviMacario commented on services/gestaoUsuarios.js
>      requestData.append('nome_usuario', dados.nome);
Podemos seguir no modelo atual.

2024-01-31 13:30 UTC, LeviMacario approved these changes

2024-02-08 22:43 UTC, merged