[Gestão de usuários] Adiciona nova página
ImpulsoGov/ImpulsoPrevine pull request #178
Opened 2024-01-23 04:24 UTC by tainnaps

2024-01-23 21:02 UTC, LeviMacario requested changes

2024-01-23 21:02 UTC, LeviMacario commented on services/gestao_usuarios/CadastrarUsuario.js
> +    maxBodyLength: Infinity,
Infinity no maxBodyLength? Qual o volume de informação que se espera ter de retorno em uma API de cadastrar usuário?
Eu reconsideraria o uso do Infinity aqui. Estamos abrindo portas de segurança, uso de computação em desperdício.
Aqui 2MB daria conta, que é o default do axios -> maxBodyLength: 2000.

2024-01-24 19:19 UTC, tainnaps commented on helpers/RequisicoesConcorrentes.js
> +    // if (result.success) {
Removido ✅

2024-01-24 19:39 UTC, tainnaps commented on pages/gestao-usuarios/cadastro/lotes/index.js
> +const Tratamento = async (data, setDadosReq) => {
@LeviMacario boa ideia! Levei as duas funções para o arquivo `/utils/cadastroUsuarios.js`. O que acha da nomeclatura?

2024-01-24 19:45 UTC, tainnaps commented on services/gestao_usuarios/CadastrarUsuario.js
> +    maxBodyLength: Infinity,
Boa observação. Removi o `maxBodyLength: Infinity` da configuração da requisição, deixando o valor padrão do axios

2024-01-24 19:54 UTC, tainnaps commented on pages/gestao-usuarios/gestao-trilha/index.js
> +    "usuarios": 14,
Chequei com Danilo e ele comentou que esses são os dados reais da gestão de trilhas e que não mudaram desde então. Esses dados não estão dinâmicos no momento porque o endpoint deles ainda será implementado.

2024-01-31 13:33 UTC, LeviMacario approved these changes

2024-01-31 13:33 UTC, LeviMacario commented on pages/gestao-usuarios/gestao-trilha/index.js
> +    "usuarios": 14,
Tranquilo, entendido! ✅

2024-02-21 00:34 UTC, merged